version: "3.8"

services:
  task-download-video:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-download-video
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: task-download-video-dev
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  task-extract-sound:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-extract-sound
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: task-extract-sound-dev
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  task-transcript-audio:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: task-transcript-audio
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: task-transcript-audio-dev
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cargo-cache:
  target-cache:
